name: Build Check

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
    unit_test:
      name: check unit_test.
      runs-on: macos-14
      steps:
        - name: Step 1:checkout
          uses: actions/checkout@v4
          with:
            submodules: true
        - name: Step 2:build test
          run:  make test
