name: Build Check

on:
  push:
    branches:
      - main # push to main
      - release/* # push to release
  pull_request:
    branches:
      - main # pr opened targeting main
      - release # pr opened targeting release
  workflow_dispatch:

jobs:
    norm:
      name: check format(norminette).
      runs-on: macos-latest
      steps:
        - name: Step 1:checkout repo
          uses: actions/checkout@v4
        - name: Step 2:install norm
          run: |
            python3 -m pip install --upgrade pip setuptools
            python3 -m pip install norminette
        - name: Step 3:run norm
          run: make norm

    check:
      name: check forbidden functions.
      runs-on: macos-14
      steps:
        - name: Step 1:checkout
          uses: actions/checkout@v4
        - name: Step 2:build
          run:  make
        - name: Step 3:run cmd.
          run: test/check_allowed_functions.sh

    unit_test:
      name: check unit_test.
      runs-on: macos-14
      steps:
        - name: Step 1:checkout
          uses: actions/checkout@v4
        - name: Step 2:build test
          run:  make test
