name: release/main-branch Check

on:
  push:
    branches:
      - main
      - 'release/**'
      - '!develop'
  pull_request:
    branches:
      - main
      - 'release/**'
      - '!develop'
  workflow_dispatch:

jobs:
    norm:
      name: check format(norminette).
      runs-on: macos-latest
      steps:
        - name: Step 1:checkout repo
          uses: actions/checkout@v4
          with:
            submodules: true
        - name: Step 2:install norm
          run: |
            python3 -m pip install --upgrade pip setuptools
            python3 -m pip install norminette
        - name: Step 3:run norm
          run: norminette src
    # forbidden:
    #   name: check forbidden functions.
    #   runs-on: macos-latest
    #   steps:
    #     - name: Step 1:checkout
    #       uses: actions/checkout@v4
    #       with:
    #         submodules: true
    #     - name: Step 2:build
    #       run:  make
    #     - name: Step 3:run cmd.
    #       run: test/check_allowed_functions.sh
